services:
  # Сервис базы данных PostgreSQL
  postgres:
    image: postgres:17.4 # Используем официальный образ PostgreSQL 15
    container_name: reminder-db # Имя контейнера для удобства
    environment:
      # Задаем переменные окружения для создания БД и пользователя
      POSTGRES_DB: reminder_db      # Имя базы данных
      POSTGRES_USER: ${DB_USERNAME}     # Имя пользователя - не цепляет через ${DB_USERNAME} и файл env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Пароль
    ports:
      - "5433:5432" # Пробрасываем порт: внешний_порт:внутренний_порт
      # Локально будешь подключаться к localhost:5433, чтобы не конфликтовать с возможным локально установленным PostgreSQL на 5432 порту.
    volumes:
      - postgres_data:/var/lib/postgresql/data # Том для сохранения данных БД между запусками
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck: # Проверка здоровья, чтобы приложение ждало готовую БД
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d reminder_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Сервис Spring Boot приложения reminder
  app:
    build: . # Говорит: "Собери образ из Dockerfile, который лежит в текущей папке"
    container_name: reminder-app
    ports:
      - "8080:8080" # Пробрасываем порт приложения
    environment:
      # Передаем переменные окружения, которые мы указали в application.properties
#      DB_URL: jdbc:postgresql://postgres:5432/reminder_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker

      # Gmail для отправки писем
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}

      # OAuth2 Google
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Telegram Bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
    depends_on:
      postgres:
        condition: service_healthy

  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: reminder-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

  # Grafana для визуализации
  grafana:
    image: grafana/grafana:latest
    container_name: reminder-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Можно поменять или использовать переменную
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning  # опционально: автоконфигурация
    restart: unless-stopped
# Определяем том в конце файла - ЭТО ВАЖНО!
volumes:
  postgres_data:
  prometheus_data:
  grafana_data: