spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: reminder
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
  liquibase:
    default-schema: reminder  # все таблицы Liquibase и твои будут здесь
    liquibase-schema: reminder  # служебные таблицы тоже будут в reminder
#    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
#    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: smothivan@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  quartz:
#    job-store-type: memory  # или jdbc для персистентности
    scheduler-name: myScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
  application:
    name: reminder
app:
  pagination:
    default-page-size: 10
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

management: #Корневой раздел для настройки всех management-функций Spring Boot Actuator
  endpoints: #Секция конфигурации эндпоинтов (HTTP-точек доступа), которые Actuator предоставляет для мониторинга и управления приложением
    web: #Настройка曝光 эндпоинтов через веб (HTTP). Альтернативы — JMX, SSH
      exposure: # какие эндпоинты публикуются наружу
        include: health,info,prometheus #Список эндпоинтов, которые нужно включить
        #health — показывает статус приложения и всех его зависимостей
        #info — выдаёт произвольную информацию о приложении
        #prometheus — эндпоинт, который отдаёт метрики в формате, понятном Prometheus
  prometheus: #конфигурации конкретно для Prometheus-экспорта
    metrics:
      export:
        enabled: true # С true — эндпоинт /actuator/prometheus начинает работать (стоит по дефлоту)
logging:
  pattern:
    console: "%d [%X{traceId}] [%X{userId}] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        security:
#          authentication: DEBUG
#    org.springframework.session: DEBUG
#    org.springframework.data.redis: DEBUG